### ISSUE TITLE
How to save/load the hashmap object

### ISSUE THREAD

**Issue by ys08** [nathan-russell/hashmap#3]
1. I used `saveRDS` function to save hashmap object
2. But got these errors when operating on the hashmap object loaded by `readRDS` function 
   **Error in .External(list(name = "CppMethod__invoke_notvoid", address = <pointer: (nil)>,  : NULL value passed as symbol address**

Thanks.

**Comment by nathan-russell** [comment]
Yes unfortunately you will not be able to do this directly with `saveRDS` / `readRDS` because the object created by `hashmap` is a bit more complicated than native R objects. However, I'm pretty sure it is possible to provide equivalent functionality by serializing / deserializing the underlying C++ object. I'll look into it and see what I can come up with.

**Comment by ys08** [comment]
Glad to hear that the problem is solvable. How about compressing the serialization of the C++ object like `saveRDS`.
