### ISSUE TITLE
"Error: external pointer is not valid" when using inside a package

### ISSUE THREAD

**Issue by blaiseli** [nathan-russell/hashmap#6]
I used the hashmap sucessfully in some R script. I later decided to put some of my functions in a package as described here: https://hilaryparker.com/2014/04/29/writing-an-r-package-from-scratch/

I load my package using the `library` command.

When I call the package-exported function that internally uses a hashmap (created within the same package file but outside the function), I get an error: "Error: external pointer is not valid", (just when the hashmap is used, according to my debugging prints).

I'm not yet very familiar with R, so I might be doing things wrong. Any idea of a typical cause for such an error ?

Thanks in advance

**Comment by nathan-russell** [comment]
Can you provide a small example that reproduces the error?

**Comment by blaiseli** [comment]
I created a "test" package based on the example in https://hilaryparker.com/2014/04/29/writing-an-r-package-from-scratch/.

I have the following code in the "test/R/test.R" file:

``` R
library(hashmap)
conversion_table <- read.table("to_caps.txt", stringsAsFactors = FALSE)

to_caps <- hashmap(conversion_table$V1, conversion_table$V2)

#' @export
convert_letters <- function(letter_vector) {
    new_letters <- to_caps$find(letter_vector)
    return(new_letters)
}
```

and the "test/to_caps.txt" file contains the following lines:

```
a   A
b   B
c   C
d   D
e   E
```

I added a "test/install.R" script to automate the installation: 

``` R
#!/usr/bin/env Rscript
library("devtools")
library(roxygen2)

document()
install("../test")
```

I install running `./install.R` from the "test" directory:

```
Updating test documentation
Loading test
Loading required package: methods
Installing test
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet  \
  CMD INSTALL '/home/bli/src/bioinfo_utils/test'  \
  --library='/home/bli/R/x86_64-pc-linux-gnu-library/3.3' --install-tests 

* installing *source* package ‘test’ ...
** R
** preparing package for lazy loading
** help
No man pages found in package  ‘test’ 
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (test)
Reloading installed test
```

Here is what happens when I use it in a interactive R session:

``` R
> library(test)
> letter_vector <- c("a", "b", "a", "d", "d")
> test::convert_letters(letter_vector)
Error: external pointer is not valid
> 
```

I work under Xubuntu 16.04 and I run R version 3.3.1, if that matters.

**Comment by blaiseli** [comment]
Actually, the problem occurs even if the hashmap is directly exported by my package and I try to use it in my R interactive session.

**Comment by nathan-russell** [comment]
I was able to reproduce the error with the example you provided, and it was more or less for the reason that I expected. In most situations (re: when dealing with ordinary R objects) your approach would work fine, but `hashmap` objects are a little different since they utilize external pointers to store their underlying data in a C++ class. We don't need to get into the gory details, but essentially this means that `hashmap` objects cannot be directly saved and loaded in the way that ordinary R objects (`data.frame`, `matrix`, `list`, etc.) can, e.g. using `save` / `load`, `saveRDS` / `readRDS`, and so on. In your source file `test.R`, when you created these objects 

``` r
conversion_table <- read.table("to_caps.txt", stringsAsFactors = FALSE)
to_caps <- hashmap(conversion_table$V1, conversion_table$V2)
```

and referenced them inside of `convert_letters`, they became a part of the environment that encapsulates the `convert_letters` function:

``` r
ls.str(environment(testpkg::convert_letters))
# conversion_table : 'data.frame':  5 obs. of  2 variables:
#  $ V1: chr  "a" "b" "c" "d" ...
#  $ V2: chr  "A" "B" "C" "D" ...
# convert_letters : function (letter_vector)  
# to_caps : Reference class 'Rcpp_Hashmap' [package "hashmap"] with 0 fields
#  list()
#  and 37 methods, of which 23 are  possibly relevant:
#    [[, [[<-, bucket_count, cache_keys, cache_values, clear, data, empty, erase, finalize, find, has_key,
#    has_keys, hash_value, initialize, insert, keys, keys_cached, rehash, renew, size, values, values_cached
```

AFAIK, what happens when you do this in a package source file is that R will save & load the objects that are part of the function's environment (probably via `save` & `load`); it will **not** re-rerun those lines of code and create fresh objects for `conversion_table` and `to_caps`. As I noted earlier, this will not work with objects utilizing external pointers, such as `to_caps`. To demonstrate the difference between a "fresh" `hashmap` and the one that is being manipulated by `convert_letters`: 

``` r
x <- read.table(
    system.file(
        "extdata",
        "to_caps.txt",
        package = "testpkg"
    ),
    stringsAsFactors = FALSE
)

h <- hashmap::hashmap(x$V1, x$V2)

h$.pointer
# <pointer: 0x000000000c377580>
#           ^^^^^^^^^^^^^^^^^^  valid memory address

environment(testpkg::convert_letters)$to_caps$.pointer
# <pointer: (nil)>
#           ^^^^^  NOT a valid memory address 
```

As you can see, the stored object `to_caps` does not have a valid memory address, which is why you get the following error if you try to actually do anything with it: 

``` r
convert_letters(letter_vector)
# Error in eval(substitute(expr), envir, enclos) : 
#   external pointer is not valid
```

On the other hand, `h` does have a valid (non-null) external pointer, so it works fine: 

``` r
h$find(letter_vector)
# [1] "A" "B" "A" "D" "D"
```

---

As far as solutions go, this is kind of a tricky situation, but I would advise you do the following: 
1. Instead of defining `conversion_table` and `to_caps` inside of the source file housing `conversion_function`, you should ship them in your package as internal data -- see [this article](http://r-pkgs.had.co.nz/data.html#data-sysdata) for reference. In this approach, such objects are essentialy global variables that you can refer to / use _from within package source code_, but are not directly accessible to users of your package, which I think is what you want. For your example, the code would look like this: 
   
   ``` r
   # run this once in an R session from 
   # the package's root directory, don't
   # include it in a package source file
   conversion_table <- read.table(
       text ="a   A
       b   B
       c   C
       d   D
       e   E",
       stringsAsFactors = FALSE
   )
   
   internal.env <- new.env()
   internal.env$to_caps <- hashmap::hashmap(
       conversion_table$V1,
       conversion_table$V2
   )
   
   devtools::use_data(
       conversion_table,
       internal.env,
       internal = TRUE,
       overwrite = TRUE
   )
   ```
2. Having done this, you can directly refer to `conversion_table` and `internal.env$to_caps` inside of `conversion_function` (no need to recreate them via `read.table`, etc.). `conversion_table` will work correctly "out-of-the-box" since it is an ordinary object and R knows how to save & load it properly; so nothing else is required there. To deal with the fact that `to_caps` houses an external pointer, you will just need to add some defensive code to make sure that the object is valid, and if it is not, recreate it by calling `hashmap::hashmap(conversion_table$V1, conversion_table$V2)`. Ideally, this should only happen the first time `conversion_function` is called during an R session. The object should remain valid for the rest of the session. I've demonstrated this [here](https://github.com/nathan-russell/testpkg/blob/master/R/test2.R), i.e. 
   
   ``` r
   convert_letters2 <- function(letter_vector) {
       ptr.address <- capture.output(
           internal.env$to_caps$.pointer
       )
       if (ptr.address == "<pointer: (nil)>") {
           ## for debugging only
           cat("Initializing internal.env$to_caps.\n")
           internal.env$to_caps <- hashmap::hashmap(
               conversion_table$V1,
               conversion_table$V2
           )
       }
   
       new_letters <- internal.env$to_caps$find(letter_vector)
       new_letters
   }
   ```

Using the [test package uploaded here](https://github.com/nathan-russell/testpkg), this seems to work: 

``` r
library(testpkg)
letter_vector <- c("a", "b", "a", "d", "d")

convert_letters2(letter_vector)
# Initializing internal.env$to_caps.
# [1] "A" "B" "A" "D" "D"

convert_letters2(letter_vector)
# [1] "A" "B" "A" "D" "D"

convert_letters2(letter_vector)
# [1] "A" "B" "A" "D" "D"
```

---

This may seem a little overwhelming to you as someone new to R, so let me know if you need clarification on anything discussed above. Generally speaking package development is much more straightforward than this, but the involvement of external pointers slightly complicates things. A pretty similar topic is touched on in issue #3, and once I've added the ability to save and load `hashmap` objects it should simplify what you are trying to do a little bit. I would also recommend going through [this reference](http://r-pkgs.had.co.nz/intro.html) when you have the time, as it is quite a bit more comprehensive than the blog post tutorial you cited.

**Comment by blaiseli** [comment]
Thanks for your detailed explanations.

I actually may want the hashmap to be accessible to the package user, so, for the moment, I ended up re-creating it in the calling context.

Besides, the conversion function was a simplified use case. In my real code, I do other things in the function that uses the hashmap, so I made the hashmap a parameter of the function.

Thanks for the reading material.
