### ISSUE TITLE
Interfacing hashmap from another package.

### ISSUE THREAD

**Issue by DominikMueller64** [nathan-russell/hashmap#7]
I would find it useful to be able to pass `hashmap` objects from R to my C++ routines, because `Rcpp::List` only allows Strings as "keys", but ideally I would need Integers. Is this currently possible/supported?

As you explained in http://stackoverflow.com/questions/42261822/c-interface-with-rcppinterfaces-not-working-for-a-function-returning-stdpa (again, best thanks for that), I tried `// [[Rcpp::depends(hashmap)]]` and `#include <hashmap.h>` as well as adding hashmap to the LinkingTo field in DESCRIPTION. I then tried
`
using namespace hashmap;
typedef HashTemplate<int, Rcpp::IntegerVector> hmap;
`,
which, however, doesn't work when I use `const hmap& foo` in a function signature.

I also tried including `#include <hashmap/HashTemplate.hpp>`, but this didn't help.

**Comment by nathan-russell** [comment]
Unfortunately this isn't supported at the moment. I plan on refactoring a lot of the internals and providing a cleaner C++ interface at some point in the future, but I have been pretty short on spare time over the past several months. For the time being, you might be able to get away with wrapping the C++ object in an `Rcpp::XPtr`. Depending on the depth of functionality required from the R side, you will have to write helper functions to operate on the external pointer as needed. As a small (and minimally tested) example, 

```c++
// [[Rcpp::depends(hashmap,BH)]]
#include <Rcpp.h>
#include <hashmap.h>
#include <boost/lexical_cast.hpp>

using namespace Rcpp;

typedef hashmap::ii_hash hmap;        // ---> typedef HashTemplate<int, int> ii_hash;
typedef XPtr<hmap> hmap_ptr_t;

// [[Rcpp::export]]
hmap_ptr_t make_hmap(IntegerVector keys, IntegerVector values)
{ return hmap_ptr_t(new hmap(keys, values)); }

// [[Rcpp::export]]
IntegerVector hmap_keys(const hmap_ptr_t ptr)
{ return clone(ptr->keys()); }

// [[Rcpp::export]]
IntegerVector hmap_values(const hmap_ptr_t ptr)
{ return clone(ptr->values()); }

// [[Rcpp::export]]
void print_hmap(const hmap_ptr_t ptr)
{
    IntegerVector keys = ptr->keys(), values = ptr->values();
    for (int i = 0; i < ptr->size(); i++) {
        Rcout
            << keys[i] << ": "
            << values[i] << "\n";
    }
}
``` 

```R
keys <- 1:10; values <- rpois(10, 20)
hm <- make_hmap(keys, values)

hmap_keys(hm)
# [1] 10  9  8  7  6  5  4  3  2  1

hmap_values(hm)
# [1] 17 23 20 19 20 15 17 14 25 15

print_hmap(hm)
# 10: 17
# 9: 23
# 8: 20
# 7: 19
# 6: 20
# 5: 15
# 4: 17
# 3: 14
# 2: 25
# 1: 15
```

However, note that I never really intended for client packages to use internal classes such as `HashTemplate`, so I can't guarantee that they won't change in the future (and possibly break code that uses them). In fact, there is a pretty decent chance that I *will* be making changes to backend classes, since I haven't yet committed to a stable, public API for the C++ side. 

But to be honest, if you only need one (or a few) particular hash map types (i.e. integer keys & integer values), you would probably be better of just pulling, e.g. `boost/unordered_map.hpp` and 
`boost/functional/hash.hpp` into your package and writing a small (possibly even non-templated) wrapper class around `boost::unordered_map` to suit your needs. In doing so you will be able to customize the functionality as necessary, as well as guarantee the stability of your own internals.

**Comment by DominikMueller64** [comment]
I see, I see.  It was probably somehow overly optimistic to expect this to be possible. Under these circumstances, and as I prefer a stable solution, I will stick to your last advice and write my own exposed wrapper class. Anyway, many thanks and keep up with the good work!
